### ISSUE TITLE
Title and main image

### ISSUE THREAD

**Issue by malcommac** [peremenov/seize#1]
Hi,
Thank you for this great piece of software!
It seems to work very well; a welcome introduction could be returning title and lead image of the article.

Is it based on Safari Reader?

**Comment by peremenov** [comment]
Hi. Thank you for your interest :)
Actually it could work better. There is a number of known issues. Version 0.2.0 should improve extraction quality. 

> title and lead image of the article

Good idea. Thanks!

> Is it based on Safari Reader?

The main concept of Seize was inspired by Safari Reader.
